### ISSUE TITLE
Limit input decimal places  not working

### ISSUE THREAD

**Issue by a0y1a** [changhuixu/ngx-digit-only#32] opened 2020-04-29 03:33 UTC
Digit Only input only allows three decimal places not working for me. I don't know what caused it.

See pictures below:

![0](https://user-images.githubusercontent.com/14976753/80558492-2b118d80-8a0d-11ea-8737-88e061a94519.png)
![1](https://user-images.githubusercontent.com/14976753/80558499-2fd64180-8a0d-11ea-938a-39277ae243b6.png)

**Comment by tonivj5** [comment] 2020-05-03 12:04
@a0y1a, I have test it and it works (your pattern is correct)

I think that the problem comes from `record.score`. If it has `1.1234567`, the input will reflect its value, although it's 'invalid'.

Have you fill the input by hand or it's the binded value?

**Comment by a0y1a** [comment] 2020-05-04 21:38
The binded value is zero, then I change and fill the input by hand. According to my understanding, after I typed 1.123, if I go on typing 4, it should be prevented. Do I miss something or should I do something else to implement it ?

**Comment by a0y1a** [comment] 2020-05-04 21:43
@tonivj5

**Comment by changhuixu** [comment] 2020-05-05 02:58
Hi @a0y1a, I am not able to reproduce this problem. Please try this example in [StackBlitz](https://stackblitz.com/edit/angular-sutxyg?file=src%2Fapp%2Fapp.component.html). I have tried Chrome, Edge, Firefox. All of them works, i.e., the input only allows 1.123.

I am afraid that you are using a different browser, but shouldn't matter, because keyboard event is almost generic across browsers. Another possible reason could be something like an iframe that prevents this directive act on your Angular module. 

Anyway, you can start from the StackBlitz example, and work towards your component to see if you can reproduce the error.

**Comment by a0y1a** [comment] 2020-05-05 09:57
@changhuixu  Thanks for your feedback. I use Chrome.  I tried example in StackBlitz, it works well. Then I copy the example in my project and run it in a new tab, it works not well. No error tips on chrome console. I will try to explore what causes this problem.

**Comment by changhuixu** [comment] 2020-05-12 16:03
close this issue due to lack of reproducibility.

**Closed by changhuixu** 2020-05-12 16:03 UTC
